### ISSUE TITLE
Xamarin.Forms.GoogleMaps.Clustering could not be installed in xamarin PCL project

### ISSUE THREAD

**Issue by trdevendran** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#43]
### VERSIONS

* Xamarin.Forms.GoogleMaps.Clustering - 1.0.0
* Xamarin.Forms - 4.0.0.497661
* Android/iOS - 8.1/11

### PLATFORMS

- [x] Android
- [x] iOS

### ACTUAL BEHAVIOR

I've gone through the documentation Xamarin.Forms.GoogleMaps.Clustering of Nuget to add the clustering package into my PCL project but I'm getting the below error in the console,

![image](https://user-images.githubusercontent.com/12223179/59971233-b7edee00-9595-11e9-9814-032d91af73ef.png)

```
Attempting to resolve dependencies for package 'Xamarin.Forms.GoogleMaps.Clustering.1.0.0' with DependencyBehavior 'Lowest' Resolving dependency information took 0 ms Resolving actions to install package 'Xamarin.Forms.GoogleMaps.Clustering.1.0.0'
Resolved actions to install package
'Xamarin.Forms.GoogleMaps.Clustering.1.0.0' Found package
'Xamarin.Forms.GoogleMaps.Clustering 1.0.0' in '/myProject/packages'. For adding package 'Xamarin.Forms.GoogleMaps.Clustering.1.0.0' to project 'myProject' that targets 'portable45-net45+win8+wp8+wpa81'. Install failed. Rolling back... 
Package 'Xamarin.Forms.GoogleMaps.Clustering.1.0.0 : Xamarin.Forms [3.0.0.482510, ), Xamarin.Forms.GoogleMaps [3.2.0, )' does not exist in project 'myProject' Executing nuget actions took 26.52 ms Could not install package 'Xamarin.Forms.GoogleMaps.Clustering 1.0.0'.
You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

As per the dependency need, I'm using Xamarin.Forms(4.0.0), Xamarin.Forms.GoogleMap(3.2.0) and NuGet (Version: 5.0.2.5988). So I'm thinking it's not a versioning problem. 
I just tried to add the same package into myProject.Android and it has been added but it wasn't added to myProject.iOS.
I seen that documentation never says its PCL based package or it is only for Android but I'm not sure why I'm getting this error. I wanted to add the package into PCL to handle the google map's marker as exist already.

can anyone please help me out?

**Comment by mierzynskim** [comment]
It's probably happing because I dropped the support for netstandard 1.0. Xamarin.Forms.GoogleMaps still supports it so if it's compatible with the clustering plugin, I can add it back :). Stay in touch touch for more info!

**Comment by trdevendran** [comment]
Hi mierzynskim, thanks for your valuable time.  As per your guess, I just upgraded my .netstandard version into latest but still I'm getting error as I attached the console log. 
Note:
Now I tried to install with VS in windows machine and previously tried with Mac.(just FYI)
![picturemessage_3hsjcn3p yyf](https://user-images.githubusercontent.com/12223179/60016742-a6473c00-96a4-11e9-9f92-bedcf3e433bb.png)

**Comment by mierzynskim** [comment]
@trdevendran I've released version 1.0.1 where I've added back support for netstandard1.0 (profile 259). I hope it helps to install the library. I would recommend you to port your library to netstandard2.0 if it's doable in your case. netstandard1.0 support may be dropped by the Xamarin.Forms.GoogleMaps library and I will have to drop it again.

**Comment by trdevendran** [comment]
Hi @mierzynskim thanks for your quick action and now I'm able to add the library in both PCL and Android project but still not able to add in iOS project , so getting  compile error as per screenshot.. 
<img width="1199" alt="Screenshot 2019-06-27 at 3 44 16 PM" src="https://user-images.githubusercontent.com/12223179/60258619-24008700-98f3-11e9-8069-35f0c26d1f65.png">
Note:
I do remember your documented instruction that I need to follow up the below,
[[assembly: ExportRenderer(typeof(ClusteredMap), typeof(ClusteredMapRenderer))]](https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#usage)

**Comment by mierzynskim** [comment]
Quick fix would be to install https://www.nuget.org/packages/Xamarin.Google.iOS.Maps.Utility/ manually. Can you share your project with me or if it's impossible create a reproduction project? I'm curious what causes the problem

**Comment by trdevendran** [comment]
@mierzynskim Thanks for your patience and helping me lot. As you suggested above for utility library,  I installed and I could add the cluster library for iOS and all other platforms but still I'm getting build error as below screenshot,
<img width="1199" alt="Screenshot 2019-06-27 at 10 31 49 PM" src="https://user-images.githubusercontent.com/12223179/60285853-1287a100-992c-11e9-8e87-6f93e02d5b05.png">
Note:
For the better observation I just reverted and install only on the PCL, though I'm getting same error.

**Comment by mierzynskim** [comment]
@trdevendran Did you resolve your problem? It looks like you installed Xamarin.Forms 3.0.0 (you mentioned had 4.0.0.497661)
